language: node_js
node_js:
- 4.3.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: f96507c6e4ac061e4bc03a1191cdca4d781b322a79b3507ce690d413b3e83ae6
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: VkDSjJW79ZDBmdfj45GXyjM1mhWG+RB/z6PbqwqGVJrQ3GVhNDHGSmF2sxE39Xsl3sW76vaIRXyKGhXmoWgYNV4WdVtF57ZomjKYPcubDR8FBmuCxhqQ4ggMmaOf5A8q1eCFV+7ac7VeWIqZzUye5TJgZg1NZwOuBbxwwe63k0oLjsmfmz5jlGwvt2rIkSxoKqeZN45rgRIa0b2o5+99ugS/CVDbYBi0GooeAeoiKchNmHxY2KXfby0lO9b2VK9fXpkZGa2gnXJFPTuvVw7ybS07/X+NcpQq+kJBv6jXaGIZzXuDLhHpYCU495NucFFEa5dv90K8JoC/qP0Jnkj/0z4wvwgwRcUX+DNPgjWPisO9AXylo/XS7Y7OpP29Pm18Tfk/DSNirHHPIDT6kSigjMV7folk+lsAaCd3RE0Xlz6yIoEXLYaja3w8XLzt67xh635zSuWs8UZXRh4atdkCkOkLj2jvD2oSdeBH6mmCERt8pnS41syZuuSK8XBkcKk21R+K1nMU9tVk20fdF30pV1FcILeLSK1zKhYnTPKdhmEjRxCBc1g0ZvA00Oa3/Yyo7qIJkNtWvNpUs/Rxt3papnfYj3khv8aCTVDoyMoDPXYVs7MlJjLf1UWo7dz4S5K1e44f28uKD2h74jgckX02LzW3+BpSBHKBT5NOi3CAAKk=
  on:
    tags: true
    repo: yoctore/yocto-utils
before_install: npm install -g grunt-cli
install: npm install
