language: node_js
node_js:
- 8.9.4
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: f96507c6e4ac061e4bc03a1191cdca4d781b322a79b3507ce690d413b3e83ae6
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: UdhNoxfchANfPAR/x+pu8Or7l1Mcn5J9nT4zDPlQ332++Z9iOwgR76BmmN2hKZcNRcXjhVjT+/kghd0glzd0mupbhvjKtWjWb8aHKWNpthnKZYww+8ht2AjawmEe2mF3UyXDYwNdjx0IYhj/NZUwJCrHwpMgC58gzby3IKWkvBrgYmNnK7sDoTajEPOZE5dZzmqbWTaOxuIvGQZTXIw/hYtMvil250AYuNfcP5odII4R/MTAKnA4xqr/duvtU+OExxRT3WDJDFXYJ63PmnY/NXcEH/xbRh5TCmeNSiQRsLLzgRZ/8mXeIOjjg/brB69WeI0/DRI0lNdRRt3DEmkXtRb4jJFFbTTAAcoka2mla66P5CbmOUATfNv5KfuNOQfrbcvjEwYlC+VEMd4kembp8QrhI2A+M0oFjd3257w4ChjBmcHJE3iJxlRsAznvZlMN6nv5i0Uaqw2so1MDXnxRJgewOJ91SSFj/L/Dk5MDUIhaAeVBS2ehXJ8XrnCOgEqA/8llqmYDCM2Z9MUez7/UrSxgy3RLjRri7yc0m0uw2FYTNWPhOElT0jrvQdQrEDwCGoeZdX7kdX8y4WZ3HyWZH0e0jIQ3iGPAQAhzOMY9XxckavRH0KV/PjBWOZpVyHX1gXYFhO0CHHC3foYSNNKV94xqFs0+KnKksbGw5Bez584=
  on:
    tags: true
    repo: yoctore/yocto-utils
before_install: npm install -g grunt-cli
install: npm install
